### ISSUE TITLE
Create class for Lines (linear)

### ISSUE THREAD

**Issue by mantaur** [KTH-Software-Engineering-DD2480/decide#32]
Some LICs are concerned with lines between points, so a common class to hold linear lines' data (mx + b) with failsafe methods for handling/calculating infinite or zero slope (and avoid division by zero) is needed.

**Comment by nolanderc** [comment]
An alternative approach would be to only store the line’s start and end points. This avoids the edge case of a vertical line.

**Comment by nolanderc** [comment]
Also, if the slope formulation is ever needed, it can always be derived from the two endpoints.

**Comment by nolanderc** [comment]
Looking through the DECIDE requirements, it seems like we only need a single function: `double distance(Line, Point)` that computes the distance between a line and the given point.

**Comment by ekorre1001** [comment]
Since I need it in LIC 6, I will create that function.

**Comment by nolanderc** [comment]
Look into the vector representation of a line. Given the start and end points we can compute the line origin `c = start` and direction `v = end - start`. Then, using these values, follow the steps [here](https://math.stackexchange.com/questions/708499/finding-distance-from-point-to-line-determined-by-vector).

**Comment by ekorre1001** [comment]
I am thinking of implementing this [formula](https://brilliant.org/wiki/dot-product-distance-between-point-and-a-line/) given 3 points`double distance(start, end, p)`.
